In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
arts = pd.read_csv("Arts_Course_Taking_20260419.csv")
arts.head()

/tmp/ipykernel_2020192/2444680330.py:1: DtypeWarning: Columns (0: GK_CNT, 1: G01_CNT, 2: G02_CNT, 3: G03_CNT, 4: G04_CNT, 5: G05_CNT, 6: G06_CNT, 7: G07_CNT, 8: G08_CNT, 9: G09_CNT, 10: G10_CNT, 11: G11_CNT, 12: G12_CNT) have mixed types. Specify dtype option on import or set low_memory=False.
  arts = pd.read_csv("Arts_Course_Taking_20260419.csv")

,SY,DIST_CODE,DIST_NAME,ORG_CODE,ORG_NAME,ORG_TYPE,ART_SUBJ,STU_GRP,TOT_STU_CNT,ALL_GRDS_CNT,...,G08_CNT,G08_PCT,G09_CNT,G09_PCT,G10_CNT,G10_PCT,G11_CNT,G11_PCT,G12_CNT,G12_PCT
0,2025,0,State,0,State,State,All Subjects,All Students,"885,779","723,263",...,"62,655",90.9%,"40,643",55.8%,"37,056",51.5%,"33,566",47.1%,"36,086",50.2%
1,2025,0,State,0,State,State,Dance,All Students,"885,779","16,206",...,799,1.2%,892,1.2%,858,1.2%,823,1.2%,729,1%
2,2025,0,State,0,State,State,Media,All Students,"885,779","70,777",...,"6,811",9.9%,"9,625",13.2%,"8,324",11.6%,"7,677",10.8%,"9,995",13.9%
3,2025,0,State,0,State,State,Music,All Students,"885,779","560,415",...,"44,451",64.5%,"13,795",18.9%,"11,016",15.3%,"10,178",14.3%,"10,933",15.2%
4,2025,0,State,0,State,State,Theatre,All Students,"885,779","57,564",...,"10,136",14.7%,"3,203",4.4%,"2,422",3.4%,"2,189",3.1%,"2,785",3.9%

In [6]:
arts.where(arts["SY"] == 2025).dropna()

,SY,DIST_CODE,DIST_NAME,ORG_CODE,ORG_NAME,ORG_TYPE,ART_SUBJ,STU_GRP,TOT_STU_CNT,ALL_GRDS_CNT,...,G08_CNT,G08_PCT,G09_CNT,G09_PCT,G10_CNT,G10_PCT,G11_CNT,G11_PCT,G12_CNT,G12_PCT
0,2025.0,0.0,State,0.0,State,State,All Subjects,All Students,"885,779","723,263",...,"62,655",90.9%,"40,643",55.8%,"37,056",51.5%,"33,566",47.1%,"36,086",50.2%
1,2025.0,0.0,State,0.0,State,State,Dance,All Students,"885,779","16,206",...,799,1.2%,892,1.2%,858,1.2%,823,1.2%,729,1%
2,2025.0,0.0,State,0.0,State,State,Media,All Students,"885,779","70,777",...,"6,811",9.9%,"9,625",13.2%,"8,324",11.6%,"7,677",10.8%,"9,995",13.9%
3,2025.0,0.0,State,0.0,State,State,Music,All Students,"885,779","560,415",...,"44,451",64.5%,"13,795",18.9%,"11,016",15.3%,"10,178",14.3%,"10,933",15.2%
4,2025.0,0.0,State,0.0,State,State,Theatre,All Students,"885,779","57,564",...,"10,136",14.7%,"3,203",4.4%,"2,422",3.4%,"2,189",3.1%,"2,785",3.9%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161867,2025.0,3480000.0,Worcester,3480000.0,Worcester,District,Dance,Male,"12,477",51,...,26,2.9%,0.0,0%,1.0,0.1%,1.0,0.1%,1.0,0.1%
161868,2025.0,3480000.0,Worcester,3480000.0,Worcester,District,Media,Male,"12,477",367,...,4,0.4%,51.0,4.9%,54.0,5.2%,72.0,7.7%,106.0,10.7%
161869,2025.0,3480000.0,Worcester,3480000.0,Worcester,District,Music,Male,"12,477","8,171",...,523,58.4%,197.0,18.8%,174.0,16.8%,218.0,23.2%,188.0,19%
161870,2025.0,3480000.0,Worcester,3480000.0,Worcester,District,Theatre,Male,"12,477",365,...,83,9.3%,29.0,2.8%,50.0,4.8%,42.0,4.5%,48.0,4.8%
161871,2025.0,3480000.0,Worcester,3480000.0,Worcester,District,Visual,Male,"12,477","8,594",...,496,55.4%,208.0,19.9%,225.0,21.7%,256.0,27.2%,279.0,28.2%

In [8]:
ap_p = pd.read_csv("Advanced_Placement_(AP)_Participation_20260419.csv")

ap_p.head()

/tmp/ipykernel_2020192/186149713.py:1: DtypeWarning: Columns (0: TEST_TAKERS_CNT, 1: TESTS_TAKEN_CNT, 2: ONE_TEST_CNT, 3: TWO_TEST_CNT, 4: THREE_TEST_CNT, 5: FOUR_TEST_CNT, 6: FIVE_PLUS_TEST_CNT) have mixed types. Specify dtype option on import or set low_memory=False.
  ap_p = pd.read_csv("Advanced_Placement_(AP)_Participation_20260419.csv")

,SY,DIST_CODE,DIST_NAME,ORG_CODE,ORG_NAME,ORG_TYPE,STU_GRP,SUBJ_CAT,SUBJ,TEST_TAKERS_CNT,TESTS_TAKEN_CNT,ONE_TEST_CNT,TWO_TEST_CNT,THREE_TEST_CNT,FOUR_TEST_CNT,FIVE_PLUS_TEST_CNT
0,2025,0,State,0,State,State,All Students,All Subjects,All Subjects,"65,211","131,220","28,603","17,892","11,077","5,255","2,384"
1,2025,0,State,0,State,State,American Indian or Alaska Native,All Subjects,All Subjects,98,187,48,25,15,6,4
2,2025,0,State,0,State,State,Asian,All Subjects,All Subjects,"9,453","23,653","2,873","2,315","2,056","1,346",863
3,2025,0,State,0,State,State,Black or African American,All Subjects,All Subjects,"4,840","8,612","2,531","1,314",648,253,94
4,2025,0,State,0,State,State,Hispanic or Latino,All Subjects,All Subjects,"9,314","16,198","5,094","2,362","1,240",468,150

In [9]:
sat = pd.read_csv("SAT_Performance_20260419.csv")

In [24]:
ap_p.head()

,SY,DIST_CODE,DIST_NAME,ORG_CODE,ORG_NAME,ORG_TYPE,STU_GRP,SUBJ_CAT,SUBJ,TEST_TAKERS_CNT,TESTS_TAKEN_CNT,ONE_TEST_CNT,TWO_TEST_CNT,THREE_TEST_CNT,FOUR_TEST_CNT,FIVE_PLUS_TEST_CNT
0,2025,0,State,0,State,State,All Students,All Subjects,All Subjects,"65,211","131,220","28,603","17,892","11,077","5,255","2,384"
1,2025,0,State,0,State,State,American Indian or Alaska Native,All Subjects,All Subjects,98,187,48,25,15,6,4
2,2025,0,State,0,State,State,Asian,All Subjects,All Subjects,"9,453","23,653","2,873","2,315","2,056","1,346",863
3,2025,0,State,0,State,State,Black or African American,All Subjects,All Subjects,"4,840","8,612","2,531","1,314",648,253,94
4,2025,0,State,0,State,State,Hispanic or Latino,All Subjects,All Subjects,"9,314","16,198","5,094","2,362","1,240",468,150

In [14]:
data = {"DIST_CODE": [],
        "STU_GRP": [],
        "ALL_GRADES_CNT": [],
        "READ_WRITE_SCORE": [],
        "MATH_SCORE": []}

In [70]:
t_sat = sat.where(sat["SY"] == 2025).where(sat["STU_GRP"] == "All Students").drop(columns=["READ_SCORE", "WRITE_SCORE"]).dropna()
t_arts = arts.where(arts["SY"] == 2025).where(arts["STU_GRP"] == "All Students").where(arts["ART_SUBJ"] == "All Subjects").dropna()

In [116]:
# total_arts.groupby(["ORG_CODE"]).apply(lambda x: x)
t_satf = t_sat.filter(["ORG_CODE", "TAKEN_CNT", "READ_WRITE_SCORE", "MATH_SCORE"])
t_artsf = t_arts.drop(columns=["SY", "DIST_CODE", "ART_SUBJ", "STU_GRP"]).dropna()
t_artsf

,DIST_NAME,ORG_CODE,ORG_NAME,ORG_TYPE,TOT_STU_CNT,ALL_GRDS_CNT,ALL_GRDS_PCT,GK_CNT,GK_PCT,G01_CNT,...,G08_CNT,G08_PCT,G09_CNT,G09_PCT,G10_CNT,G10_PCT,G11_CNT,G11_PCT,G12_CNT,G12_PCT
0,State,0.0,State,State,"885,779","723,263",81.7%,"57,742",92.5%,"63,527",...,"62,655",90.9%,"40,643",55.8%,"37,056",51.5%,"33,566",47.1%,"36,086",50.2%
700,Abby Kelley Foster Charter Public (District),4450000.0,Abby Kelley Foster Charter Public (District),District,"1,424","1,355",95.2%,121,100%,123,...,108,100%,80,100%,74,87.1%,48,60%,53,69.7%
784,Abby Kelley Foster Charter Public (District),4450105.0,Abby Kelley Foster Charter Public School,School,"1,424","1,355",95.2%,121,100%,123,...,108,100%,80,100%,74,87.1%,48,60%,53,69.7%
868,Abington,10000.0,Abington,District,"2,079","1,813",87.2%,147,100%,177,...,162,98.8%,61,46.9%,87,61.3%,53,40.5%,66,53.7%
1414,Acton-Boxborough,6000000.0,Acton-Boxborough,District,"4,980","4,041",81.1%,297,100%,364,...,381,92%,278,68.3%,228,56.6%,117,28.1%,125,32%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156760,Winchendon,3430000.0,Winchendon,District,"1,119","1,055",94.3%,77,100%,83,...,92,94.8%,51.0,69.9%,52.0,80%,49.0,77.8%,50.0,86.2%
157288,Winchester,3440000.0,Winchester,District,"4,337","3,331",76.8%,0,0%,311,...,342,98.6%,230.0,60.1%,193.0,56.1%,166.0,45.1%,126.0,40%
157594,Winthrop,3460000.0,Winthrop,District,"1,961","1,673",85.3%,151,100%,141,...,153,99.4%,110.0,82.7%,49.0,29.7%,63.0,44.4%,84.0,55.3%
158548,Woburn,3470000.0,Woburn,District,"4,366","3,656",83.7%,345,100%,352,...,339,98.3%,161.0,52.3%,153.0,46.5%,112.0,38.2%,148.0,43.7%
161788,Worcester,3480000.0,Worcester,District,"24,269","19,564",80.6%,"1,962",99.8%,"1,892",...,"1,660",94.4%,813.0,39.1%,899.0,44.5%,986.0,52.9%,956.0,49.4%

In [117]:
df = t_artsf.drop(columns=[item for item in t_arts if item.endswith("CNT")]).merge(t_satf, on="ORG_CODE")

In [118]:
df.drop(columns=["DIST_NAME", "ORG_CODE", "ORG_NAME", "ORG_TYPE"]).replace(",","", regex=True).replace("\%","", regex=True).corr()

<>:1: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
<>:1: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
/tmp/ipykernel_2020192/4228435517.py:1: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
  df.drop(columns=["DIST_NAME", "ORG_CODE", "ORG_NAME", "ORG_TYPE"]).replace(",","", regex=True).replace("\%","", regex=True).corr()

,ALL_GRDS_PCT,GK_PCT,G01_PCT,G02_PCT,G03_PCT,G04_PCT,G05_PCT,G06_PCT,G07_PCT,G08_PCT,G09_PCT,G10_PCT,G11_PCT,G12_PCT,TAKEN_CNT,READ_WRITE_SCORE,MATH_SCORE
ALL_GRDS_PCT,1.000000,0.475930,0.593137,0.646848,0.687537,0.691124,0.686955,0.712187,0.200236,0.182037,0.320628,0.591083,0.580911,0.505302,-0.039188,0.085219,0.112702
GK_PCT,0.475930,1.000000,0.533118,0.459301,0.372166,0.373716,0.366000,0.408219,0.048770,-0.039566,-0.092913,0.054396,0.141814,0.130066,-0.007367,0.015978,0.021351
G01_PCT,0.593137,0.533118,1.000000,0.864463,0.701166,0.703715,0.693885,0.607055,-0.046704,-0.061293,-0.126245,0.125152,0.169830,0.157648,0.006511,0.093787,0.110056
G02_PCT,0.646848,0.459301,0.864463,1.000000,0.809829,0.812307,0.804200,0.716796,-0.017602,-0.040716,-0.118817,0.186374,0.216751,0.179083,0.005328,0.105294,0.132755
G03_PCT,0.687537,0.372166,0.701166,0.809829,1.000000,0.994894,0.985831,0.890279,-0.018338,-0.044684,-0.101577,0.265896,0.271778,0.274665,0.002728,0.148917,0.173726
G04_PCT,0.691124,0.373716,0.703715,0.812307,0.994894,1.000000,0.988410,0.885349,-0.021087,-0.040169,-0.100703,0.273584,0.264906,0.273012,0.004122,0.148295,0.173609
G05_PCT,0.686955,0.366000,0.693885,0.804200,0.985831,0.988410,1.000000,0.887889,-0.018740,-0.030498,-0.100352,0.270962,0.253469,0.258969,0.004540,0.145838,0.176058
G06_PCT,0.712187,0.408219,0.607055,0.716796,0.890279,0.885349,0.887889,1.000000,0.177953,0.099540,-0.048804,0.270199,0.224764,0.263382,-0.020741,0.213583,0.226982
G07_PCT,0.200236,0.048770,-0.046704,-0.017602,-0.018338,-0.021087,-0.018740,0.177953,1.000000,0.575188,0.051948,0.023581,-0.079005,-0.040433,-0.021623,0.072437,0.097819
G08_PCT,0.182037,-0.039566,-0.061293,-0.040716,-0.044684,-0.040169,-0.030498,0.099540,0.575188,1.000000,0.032395,0.040905,-0.059980,-0.055782,-0.009360,0.051154,0.072295
G09_PCT,0.320628,-0.092913,-0.126245,-0.118817,-0.101577,-0.100703,-0.100352,-0.048804,0.051948,0.032395,1.000000,0.593458,0.324381,0.086600,-0.036736,0.024562,0.005708
G10_PCT,0.591083,0.054396,0.125152,0.186374,0.265896,0.273584,0.270962,0.270199,0.023581,0.040905,0.593458,1.000000,0.509591,0.290220,-0.031251,0.031290,0.055257
G11_PCT,0.580911,0.141814,0.169830,0.216751,0.271778,0.264906,0.253469,0.224764,-0.079005,-0.059980,0.324381,0.509591,1.000000,0.601481,-0.025981,-0.034621,-0.085340
G12_PCT,0.505302,0.130066,0.157648,0.179083,0.274665,0.273012,0.258969,0.263382,-0.040433,-0.055782,0.086600,0.290220,0.601481,1.000000,-0.033656,0.004540,-0.042082
TAKEN_CNT,-0.039188,-0.007367,0.006511,0.005328,0.002728,0.004122,0.004540,-0.020741,-0.021623,-0.009360,-0.036736,-0.031251,-0.025981,-0.033656,1.000000,0.005347,0.021923
READ_WRITE_SCORE,0.085219,0.015978,0.093787,0.105294,0.148917,0.148295,0.145838,0.213583,0.072437,0.051154,0.024562,0.031290,-0.034621,0.004540,0.005347,1.000000,0.942801
MATH_SCORE,0.112702,0.021351,0.110056,0.132755,0.173726,0.173609,0.176058,0.226982,0.097819,0.072295,0.005708,0.055257,-0.085340,-0.042082,0.021923,0.942801,1.000000

In [ ]:
"